### PR TITLE
Correct Service Install Folder to clean 

### PR DESCRIPTION
**Pull request by nasc17**

### CODE REVIEW

**Review by DaeunYim — COMMENTED** [review]
Is this a fix for issue 427? In that case, I think we need extensive tests like making online package -> downloading pgtoolsservice and repeating delete, download steps multiple times to see if it creates the same number of temp folders or not

**Comment by nasc17** [comment]
> Is this a fix for issue 427? In that case, I think we need extensive tests like making online package -> downloading pgtoolsservice and repeating delete, download steps multiple times to see if it creates the same number of temp folders or not

This is at least the start. Checking to see how we were cleaning and that file path it was defining is not what we actually have. We can start to tests more with unstable build.

**Comment by DaeunYim** [comment]
> > Is this a fix for issue 427? In that case, I think we need extensive tests like making online package -> downloading pgtoolsservice and repeating delete, download steps multiple times to see if it creates the same number of temp folders or not
> 
> This is at least the start. Checking to see how we were cleaning and that file path it was defining is not what we actually have. We can start to tests more with unstable build.

I was thinking without merging this and waiting for unstable build, simply making a vsix file in your local version should be enough for testing

**Review by DaeunYim — APPROVED** [review]
I think this is good fix anyway

**Pull request merged**
